#+TITLE: org-hexo -- org-mode exporter for Hexo

*THIS PROJECT IS DEAD*:

I am porting this to my fork of [[https://github.com/coldnew/hexo-renderer-org][hexo-renderer-org]], which now can use emacs to htmlize the code block.

Since [[https://github.com/coldnew/hexo-renderer-org][hexo-renderer-org]] is more easy to use instead of org-hexo, I'll working on my fork instead of mantain this project.

---

org-hexo is an org-mode exporter for [[https://hexo.io/zh-tw/][hexo]] static site generator. I write
this for my personal's [[http://coldnew.github.io][blog]].

#+BEGIN_QUOTE
This project is *DEAD*, but it's workable now.
#+END_QUOTE

*Since this project is written for myself, there's no schedule to a workable release, if you intrested in this project, please add ISSUE to make me work more quickly*


*這個專案是我為了解決自己寫 blog 需求而設計的，因此沒人要求的話很難有正式發布的時間表，如果你想使用 org-mode 在 hexo 上，請開 ISSUE 讓我知道，並加緊把這專案發佈出來*

* *TODO*

  Add full workable examples.
  
  Currently I use [[https://github.com/coldnew/emacs-blogit][emacs-blogit]] to export the org file to =source/_posts= dir. It's time to integrate all to org-hexo.

* Backend

org-hexo support following backend, which help you convert org-mode article to another type file

- [X] Markdown

  It might work, but it may have problem when you enable =htmlize=, so this feature will move to use HTML backend

- [X] HTML

  Now I use this :)

* OPTIONS

#+BEGIN_SRC org
  ,#+OPTIONS:  feed:nil
#+END_SRC
