#+TITLE: org-hexo -- org-mode exporter for Hexo

*THIS PROJECT IS DEAD*:

I am porting this to my fork of [[https://github.com/coldnew/hexo-renderer-org][coldnew/hexo-renderer-org]], which now can use emacs to htmlize the code block.

Since [[https://github.com/coldnew/hexo-renderer-org][coldnew/hexo-renderer-org]] is more easy to use instead of org-hexo, I'll working on my fork instead of mantain this project.

You can see [[https://coldnew.github.io/hexo-org-example/2017/03/05/getting-started-with-hexo-and-org-mode/][Getting Started with the Hexo and org-mode]] to know how to use [[https://github.com/coldnew/hexo-renderer-org][coldnew/hexo-renderer-org]].

*這個專案死翹翹囉*:

沒有為什麼，以前我都是用類似 =org-publish-prject= 的方式來產生 HTML 檔案讓 hexo 去進行渲染，不過隨著 org-mode 文件越來越多，整個發布流程就會慢的讓人無法接受，所以這個專案 *該死* 。

取而代之的，我 fork [[https://github.com/CodeFalling/hexo-renderer-org][CodeFalling/hexo-renderer-org]] 這個專案到 [[https://github.com/coldnew/hexo-renderer-org][coldnew/hexo-renderer-org]], 和原始版本的不同之處在於我的 fork 是用 emacs 自己去進行代碼上色，並且盡可能遵守 org-mode way。

目前已經有英文版本的 [[https://coldnew.github.io/hexo-org-example/2017/03/05/getting-started-with-hexo-and-org-mode/][Getting Started with the Hexo and org-mode]], 所以應該使用不會有任何問題才對，因此這個專案還是要死翹翹，因為我懶得維護了。 (中文版本要看心情，因為我很忙....)

BTW, [[https://github.com/coldnew/hexo-renderer-org][coldnew/hexo-renderer-org]] 某一天會送 PR 回到 [[https://github.com/CodeFalling/hexo-renderer-org][CodeFalling/hexo-renderer-org]], 不過我無法保證何時....

不管怎樣，謝謝你們關注(Star)這個專案，他雖然死掉了，但是 repo 會一直保留在 GitHub 上。


------ Following are OLD contents -------------

org-hexo is an org-mode exporter for [[https://hexo.io/zh-tw/][hexo]] static site generator. I write
this for my personal's [[http://coldnew.github.io][blog]].

#+BEGIN_QUOTE
This project is *DEAD*, but it's workable now.
#+END_QUOTE

*Since this project is written for myself, there's no schedule to a workable release, if you intrested in this project, please add ISSUE to make me work more quickly*


*這個專案是我為了解決自己寫 blog 需求而設計的，因此沒人要求的話很難有正式發布的時間表，如果你想使用 org-mode 在 hexo 上，請開 ISSUE 讓我知道，並加緊把這專案發佈出來*

* *TODO*

  Add full workable examples.
  
  Currently I use [[https://github.com/coldnew/emacs-blogit][emacs-blogit]] to export the org file to =source/_posts= dir. It's time to integrate all to org-hexo.

* Backend

org-hexo support following backend, which help you convert org-mode article to another type file

- [X] Markdown

  It might work, but it may have problem when you enable =htmlize=, so this feature will move to use HTML backend

- [X] HTML

  Now I use this :)

* OPTIONS

#+BEGIN_SRC org
  ,#+OPTIONS:  feed:nil
#+END_SRC
